steps:
- name: 'gcr.io/config-validator/make'
  args: ['test']
- name: 'gcr.io/config-validator/make'
  args: ['check_sample_files']
- name: 'gcr.io/config-validator/make'
  args: ['check_format']
- name: 'gcr.io/config-validator/policy-tool'
  args: ['lint', '--policies', './policies', '--policies', './samples', '--libs', './lib']
