apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPAppengineLocationConstraintV1
metadata:
  name: allow_appengine_applications_in_australia_and_south_america
  annotations:
    description: Restrict locations (regions) where App Engine applications are deployed.
spec:
  severity: high
  match:
    target: ["organization/*"] # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
<<<<<<< HEAD
  parameters:
=======
  parameters: 
>>>>>>> b5d66aa... Create a kpt setter to set the constraint target. Add annotations to the samples.
    locations:
    - "australia*"
    - "southamerica*"
