# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeDefaultServiceAccountConstraintV1
metadata:
  name: compute_default_service_account
  annotations:
    description: Ensure that instances are not configured to use the default service account with full access to all Cloud APIs
    # This constraint is not certified by CIS.
    bundles.validator.forsetisecurity.org/cis-v1.1: 4.01
spec:
  severity: high
  match:
    gcp:
      target: ["organization/*"]
  parameters: {}
