apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV2
metadata:
  name: restrict_owner_role
  annotations:
    description: Only my domain members are allowed to have the Owner role on projects
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organizations/**"
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: allowlist
    role: roles/owner
    members:
    - "user:*@google.com"
    - "group:*@google.com"
