apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAuditLogConstraintV1
metadata:
  name: audit_log_data_read_write
spec:
  parameters:
    services: [cloudasset.googleapis.com, sqladmin.googleapis.com]
    log_types: [DATA_READ, DATA_WRITE]
