apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAuditLogConstraintV1
metadata:
  name: audit_log_data_read_write
  annotations:
    description: Checks that the defined services have audit logs enabled (ADMIN_READ,
      DATA_READ, DATA_WRITE).
spec:
  parameters:
    services: [cloudasset.googleapis.com, sqladmin.googleapis.com]
    log_types: [DATA_READ, DATA_WRITE]
