apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV1
metadata:
  name: blacklist_all_users
  annotations:
    description: Prevent public users from having access to resources via IAM
    bundles.validator.forsetisecurity.org/scorecard-v1: security
spec:
  severity: high
  match:
    target: ["organization/*"] # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: blacklist
    role: "roles/*"
    members:
    - "allUsers"
    - "allAuthenticatedUsers"
