apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV1
metadata:
  name: blacklist_cloudasset_role
  annotations:
    description: Ban any users from being granted Service Account User access
    benchmark: CIS11_1.05
spec:
  severity: high
  match:
    target: ["organization/*"]
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: blacklist
    role: roles/iam.serviceAccountUser
    members:
      - "*"
