apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV1
metadata:
  name: blacklist_serviceaccount_user
  annotations:
    description: Ban any users from being granted Service Account User access
    # This constraint is not certified by CIS.
    bundles.validator.forsetisecurity.org/cis-v1.1: 1.05
spec:
  severity: high
  match:
    target: ["organization/*"] # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: blacklist
    assetType: cloudresourcemanager.googleapis.com/Project
    role: roles/iam.serviceAccountUser
    members:
    - "*"
