apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMRoleSeparationConstraintV1
metadata:
  name: ensure_service_account_role_separation
  annotations:
    description: Prevent public users from having access to both administer and user service accounts at the same time
    # This constraint is not certified by CIS.
    bundles.validator.forsetisecurity.org/cis-v1.1: 1.07
spec:
  severity: high
  parameters:
    roles:
      - - roles/iam.serviceAccountUser
        - roles/iam.serviceAccountAdmin
