apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPServiceUsageConstraintV1
metadata:
  name: deny_some_apis
  annotations:
    description: Deny a set of APIS
spec:
  severity: high
  match:
    target: ["organization/*"] # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    exclude: []
  parameters:
    mode: deny
    services:
    - "cloudvision.googleapis.com"
    - "translate.googleapis.com"
