apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPServiceUsageConstraintV1
metadata:
  name: deny_some_apis
  annotations:
    description: Only a basic set of APIS
spec:
  severity: high
  match:
    target: ["organization/*"]
    exclude: []
  parameters:
    mode: deny
    services:
    - "cloudvision.googleapis.com"
    - "translate.googleapis.com"

