apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPSpannerLocationConstraintV1
metadata:
  name: allow_spanner_clusters_in_asia_and_europe
  annotations:
    description: Checks Cloud Spanner locations.
spec:
  severity: high
  match:
    target: ["organization/*"]
  parameters:
    locations:
    - "asia*"
    - "eur*"
