apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPStorageLoggingConstraintV1
metadata:
  name: storage_logging
  annotations:
    description: Ensure storage logs are delivered to a separate bucket
spec:
  severity: high
  match:
    target: ["organization/*"] # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    exclude: [] # optional, default is no exclusions
  parameters: {}
