apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: noautosubnetvpc
spec:
  crd:
    spec:
      names:
        kind: NoAutoSubnetVPC
      validation:
        openAPIV3Schema:
          properties:
            allowAutoSubnet:  # This property specifies whether auto subnet creation is allowed or not
              type: boolean
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package no_autosubnet_vpc

        violation[{"msg": msg}] {
          input.review.kind == "Network"
          input.review.operation == "CREATE"
          input.review.object.spec.createSubnetwork == true
          msg := "Automatic subnet creation is not allowed for VPC networks."
        }