# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPEnforceNamingConstraintV1
metadata:
  name: enforce_naming_convention
  annotations:
    description: Checks defined resources that are supported by Cloud Asset Inventory
      are named according to regular expression pattern.
spec:
  severity: high
  parameters:
    # Provide naming patterns for each resource. You may provide more than one pattern per resource.
    # All the resources that do not follow the naming requirements are alerted. 
    # If you don't provide a rule for a resource, we simply ignore it. 
    # Or if you don't provide any pattern, we again ignore.
    naming_rules:
    - resource: "compute.googleapis.com/SslCertificate"   # asset_type field from inventory
      patterns:
      - "cert-sn-.*"
      - "cert-self-signed-.*"
    - resource: "compute.googleapis.com/Instance"         # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-(\\w+)-(\\w+)-gce-(\\d+)$"
    - resource: "sqladmin.googleapis.com/Instance"        # asset_type field from inventory
      patterns:
      - "^cloudsql-(\\w+)-mv-(\\w+)-(\\w+)-.*"
    - resource: "redis.googleapis.com/Instance"           # asset_type field from inventory
      patterns:
      - "^redis-(\\w+)-mv-(\\w+)-multi-app$"
    - resource: "storage.googleapis.com/Bucket"           # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-(\\w+)-(\\w+)$"
    - resource: "compute.googleapis.com/Network"          # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-(\\w+)-vpc-(\\d+)$"
    - resource: "compute.googleapis.com/Subnetwork"       # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-(\\w+)-(\\w+)-sn-(\\d+)$"
    - resource: "compute.googleapis.com/Route"            # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-(\\w+)-route-(\\d+)$"
    - resource: "compute.googleapis.com/Firewall"         # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-allow-(\\w+)$"
      - "^mv-(\\w+)-deny-(\\w+)$"
    - resource: "container.googleapis.com/Cluster"        # asset_type field from inventory
      patterns:
      - "^mv-(\\w+)-(\\w+)-(\\w+)-gke-(\\d+)$"

